spring:
  session:
    store-type: redis
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
  profiles:
    include: db, redis, kafka
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  sql:
    init:
      platform: MySQL
      encoding: UTF-8
      mode: never
  output:
    ansi:
      enabled: always